name: Build and Release OddEven

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Linux
        run: |
          gcc -o OddEven_Linux *.C

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: any

      - name: Build for Windows
        run: |
          cc -o OddEven_Windows.exe *.C -static

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            OddEven*
